routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::get('/', 'MainController@index')->name('index');
Route::get('/about-us','MainController@about')->name('about');
//
//Route::get('terms', function () {
//    return view('terms');
//});
//
//Route::get('policies', function () {
//    return view('policies');
//});


Route::get('image/upload','NewsController@images');
Route::get('test/{name}','CategoryController@index');
Route::get('/edit/profile', 'ProfileController@edit');
Route::post('/update/profile', 'ProfileController@update');

Route::get('/user/unsub/{id}','ProfileController@unsub');
Route::get('/user/sub/{id}','ProfileController@sub');


Route::get('profile', function () {
    return redirect('profile/' . Auth::user()->username);
});
Route::get('profile/{username}', 'ProfileController@index');
Route::get('timeline', function () {
    return redirect('timeline/' . Auth::user()->username);
});
Route::get('timeline/{username}', 'ProfileController@timeline');

Route::get('payments', 'ProfileController@payments');

Route::get('profile/{username}/presentation', 'ProfileController@presentation');

Route::get('notices', 'ProfileController@notices');

Route::get('follow/{username}', 'ProfileController@follow');
Route::get('unfollow/{username}', 'ProfileController@unfollow');


Route::get('category/{name}', 'CategoryController@index');


Route::get('readlater/{news_id}', 'MainController@read_later');
Route::get('myreads', 'MainController@my_reads');
Route::get('my_drafts', 'NewsController@my_drafts');


Route::resource('news', 'NewsController');
Route::get('togglebookmark/{id}', 'NewsController@toggle_bookmark');

Route::post('comment/publish/{id}', 'NewsController@publish_comment');
Route::get('comment/delete/{id}', 'NewsController@delete_comment');

Route::get('bookmarks', 'NewsController@get_bookmarks');
Route::get('history', 'NewsController@get_history');

Route::post('search-news', 'NewsController@search');
Route::get('delete/news/{id}','NewsController@delete');


Route::get('withdraw-paypal', 'AdminControllers\PaymentController@withdraw_paypal');
Route::get('withdraw-bank', 'AdminControllers\PaymentController@withdraw_bank');



Route::get('information', 'MainController@info_page');
Route::get('legal', 'MainController@legal_page');


Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function($router) {
    Route::get('/', 'AdminController@index');

    Route::resource('categories', 'AdminControllers\CategoryController');
    Route::resource('admins', 'AdminControllers\AdminResource');
    Route::resource('users', 'AdminControllers\UserResource');
    Route::resource('news', 'AdminControllers\NewsResource');

    Route::get('/user/{id}/suspend', 'AdminControllers\UserResource@suspend');
    Route::get('/user/{id}/unsuspend', 'AdminControllers\UserResource@unsuspend');

    Route::get('distributefunds', 'AdminControllers\PaymentController@distribute_view');
    Route::post('distributefunds', 'AdminControllers\PaymentController@distribute_funds');

    Route::get('payrequests', 'AdminControllers\PaymentController@payment_requests');
    Route::get('payrequests/paid/{id}', 'AdminControllers\PaymentController@mark_paid');

    Route::group(['prefix' => 'ads'], function($router) {
        Route::get('/', 'AdminController@ads');
        Route::post('store', 'AdminController@ads_store');
    });

    Route::group(['prefix' => 'settings'], function($router) {
        Route::get('/', 'AdminController@settings');
        Route::post('store', 'AdminController@settings_store');
    });

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'username',
        'password',
        'date_of_birth',
        'name_of_presentation',
        'profile_picture',
        'small_presentation',
        'paypal_email',
        'bank_iban',
        'bank_account_holder',
        'role_id',
        'suspended',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function news() {
        return $this->hasMany('App\News');
    }

    public function readlater() {
        return $this->hasMany('App\ReadLater');
    }

    public function readhistory() {
        return $this->hasMany('App\ReadHistory');
    }

    public function follower() {
        return $this->hasMany('App\Follower');
    }

    public function bookmark() {
        return $this->hasMany('App\Bookmark');
    }

    public function singlefollow(){
        return $this->belongsTo('App\Follower');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin.master')

@section('content')

    <!-- Start Page Content -->
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <div class="form-validation">

                        @forelse ($errors->all() as $error)
                            <div class="alert alert-danger">{{ $error }}</div>
                        @empty

                        @endforelse

                        <form class="form-valide" action="{{ route('users.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="first_name">First Name <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="last_name">Last Name <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="username">Username <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="username" name="username" placeholder="Userame">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="email">Email <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="password">Password <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="password-confirmation">Confirm Password <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="password" class="form-control" id="password-confirmation" name="password_confirmation" placeholder="Confirm Password">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="date_of_birth">Date of birth <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="date" class="form-control" id="date_of_birth" name="date_of_birth" placeholder="Date of Birth">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="role">Role <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <select name="role">
                                        <option value="1">User</option>
                                        <option value="2">Admin</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-8 ml-auto">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- End PAge Content -->

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin.master')

@section('content')

    <!-- Start Page Content -->
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <div class="form-validation">

                        @forelse ($errors->all() as $error)
                            <div class="alert alert-danger">{{ $error }}</div>
                        @empty

                        @endforelse

                        <form class="form-valide" action="{{ route('users.update', $user->id) }}" method="post">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="PATCH">
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="first_name">First Name <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" value="{{ $user->first_name }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="last_name">Last Name <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" value="{{ $user->last_name }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="username">Username <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="username" name="username" disabled placeholder="Userame" value="{{ $user->username }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="email">Email <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ $user->email }}">
                                </div>
                            </div>
                            {{--<div class="form-group row">--}}
                                {{--<label class="col-lg-4 col-form-label" for="password">Password <span class="text-danger">*</span></label>--}}
                                {{--<div class="col-lg-6">--}}
                                    {{--<input type="password" class="form-control" id="password" name="password" placeholder="Password" autocomplete="off">--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="form-group row">--}}
                                {{--<label class="col-lg-4 col-form-label" for="password-confirmation">Confirm Password <span class="text-danger">*</span></label>--}}
                                {{--<div class="col-lg-6">--}}
                                    {{--<input type="password" class="form-control" id="password-confirmation" name="password_confirmation" placeholder="Confirm Password" >--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="date_of_birth">Date of birth <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <input type="date" class="form-control" id="date_of_birth" name="date_of_birth" placeholder="Date of Birth"  value="{{ $user->date_of_birth }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="role">Role <span class="text-danger">*</span></label>
                                <div class="col-lg-6">
                                    <select name="role">
                                        <option value="1" @if ($user->role_id == 1) selected @endif>User</option>
                                        <option value="2" @if ($user->role_id == 2) selected @endif>Admin</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-8 ml-auto">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- End PAge Content -->

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin.master')

@section('content')

    <!-- Start Page Content -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Users </h4>
                    <a href="{{ route('users.create') }}" class="btn btn-primary float-right">Add User</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover ">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>First Name</th>
                                <th>Surname</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Date Of Birth</th>
                                <th>Status</th>
                                <th>Role</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($users as $key => $user)
                                <tr>
                                    <th scope="row">{{ $key + 1 }}</th>
                                    <td>{{ $user->first_name }}</td>
                                    <td>{{ $user->last_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->date_of_birth }}</td>
                                    <td>@if ($user->suspended == 0)<span class="badge badge-success">Active</span> @else <span class="badge badge-danger">Suspended</span> @endif </td>
                                    <td @if ($user->role_id == 2) class="color-success" @else class="color-primary" @endif>@if ($user->role_id == 2) Admin @else User @endif</td>
                                    <td>
                                        <form action="{{ route('users.destroy', $user->id) }}" method="POST">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            @if ($user->suspended == 0)
                                                <a href="{{ url('/admin/user/' . $user->id . "/suspend") }}" class="btn btn-outline-danger">Suspend</a>
                                            @else
                                                <a href="{{ url('/admin/user/' . $user->id . "/unsuspend") }}" class="btn btn-outline-success">Unsuspend</a>
                                            @endif
                                            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                                            <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                            <tr>
                                <td colspan="9">No Data Found!</td>
                            </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <!-- /# row -->

@endsection