routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::get('/', 'MainController@index')->name('index');
Route::get('/about-us','MainController@about')->name('about');
//
//Route::get('terms', function () {
//    return view('terms');
//});
//
//Route::get('policies', function () {
//    return view('policies');
//});


Route::get('image/upload','NewsController@images');
Route::get('test/{name}','CategoryController@index');
Route::get('/edit/profile', 'ProfileController@edit');
Route::post('/update/profile', 'ProfileController@update');

Route::get('/user/unsub/{id}','ProfileController@unsub');
Route::get('/user/sub/{id}','ProfileController@sub');


Route::get('profile', function () {
    return redirect('profile/' . Auth::user()->username);
});
Route::get('profile/{username}', 'ProfileController@index');
Route::get('timeline', function () {
    return redirect('timeline/' . Auth::user()->username);
});
Route::get('timeline/{username}', 'ProfileController@timeline');

Route::get('payments', 'ProfileController@payments');

Route::get('profile/{username}/presentation', 'ProfileController@presentation');

Route::get('notices', 'ProfileController@notices');

Route::get('follow/{username}', 'ProfileController@follow');
Route::get('unfollow/{username}', 'ProfileController@unfollow');


Route::get('category/{name}', 'CategoryController@index');


Route::get('readlater/{news_id}', 'MainController@read_later');
Route::get('myreads', 'MainController@my_reads');
Route::get('my_drafts', 'NewsController@my_drafts');


Route::resource('news', 'NewsController');
Route::get('togglebookmark/{id}', 'NewsController@toggle_bookmark');

Route::post('comment/publish/{id}', 'NewsController@publish_comment');
Route::get('comment/delete/{id}', 'NewsController@delete_comment');

Route::get('bookmarks', 'NewsController@get_bookmarks');
Route::get('history', 'NewsController@get_history');

Route::post('search-news', 'NewsController@search');
Route::get('delete/news/{id}','NewsController@delete');


Route::get('withdraw-paypal', 'AdminControllers\PaymentController@withdraw_paypal');
Route::get('withdraw-bank', 'AdminControllers\PaymentController@withdraw_bank');



Route::get('information', 'MainController@info_page');
Route::get('legal', 'MainController@legal_page');


Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function($router) {
    Route::get('/', 'AdminController@index');

    Route::resource('categories', 'AdminControllers\CategoryController');
    Route::resource('admins', 'AdminControllers\AdminResource');
    Route::resource('users', 'AdminControllers\UserResource');
    Route::resource('news', 'AdminControllers\NewsResource');

    Route::get('/user/{id}/suspend', 'AdminControllers\UserResource@suspend');
    Route::get('/user/{id}/unsuspend', 'AdminControllers\UserResource@unsuspend');

    Route::get('distributefunds', 'AdminControllers\PaymentController@distribute_view');
    Route::post('distributefunds', 'AdminControllers\PaymentController@distribute_funds');

    Route::get('payrequests', 'AdminControllers\PaymentController@payment_requests');
    Route::get('payrequests/paid/{id}', 'AdminControllers\PaymentController@mark_paid');

    Route::group(['prefix' => 'ads'], function($router) {
        Route::get('/', 'AdminController@ads');
        Route::post('store', 'AdminController@ads_store');
    });

    Route::group(['prefix' => 'settings'], function($router) {
        Route::get('/', 'AdminController@settings');
        Route::post('store', 'AdminController@settings_store');
    });

});

resources/views/layouts/admin/footer.blade.php
                </div>
                <!-- End Container fluid  -->
            <!-- footer -->
            <footer class="footer"> © 2018 All rights reserved.</footer>
            <!-- End footer -->
        </div>
        <!-- End Page wrapper  -->
    </div>
    <!-- End Wrapper -->
    <!-- All Jquery -->
    <script src="/admin-assets/js/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="/admin-assets/js/lib/bootstrap/js/popper.min.js"></script>
    <script src="/admin-assets/js/lib/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="/admin-assets/js/jquery.slimscroll.js"></script>
    <!--Menu sidebar -->
    <script src="/admin-assets/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="/admin-assets/js/lib/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <!--Custom JavaScript -->


    <!-- Amchart -->
    <script src="/admin-assets/js/lib/morris-chart/raphael-min.js"></script>
    <script src="/admin-assets/js/lib/morris-chart/morris.js"></script>
    <script src="/admin-assets/js/lib/morris-chart/dashboard1-init.js"></script>


    <script src="/admin-assets/js/lib/calendar-2/moment.latest.min.js"></script>
    <!-- scripit init-->
    <script src="/admin-assets/js/lib/calendar-2/semantic.ui.min.js"></script>
    <!-- scripit init-->
    <script src="/admin-assets/js/lib/calendar-2/prism.min.js"></script>
    <!-- scripit init-->
    <script src="/admin-assets/js/lib/calendar-2/pignose.calendar.min.js"></script>
    <!-- scripit init-->
    <script src="/admin-assets/js/lib/calendar-2/pignose.init.js"></script>

    <script src="/admin-assets/js/lib/owl-carousel/owl.carousel.min.js"></script>
    <script src="/admin-assets/js/lib/owl-carousel/owl.carousel-init.js"></script>
    <script src="/admin-assets/js/scripts.js"></script>
    <!-- scripit init-->

    <script src="/admin-assets/js/lib/toastr/toastr.min.js"></script>
    <!-- scripit init-->
    {{--<script src="/admin-assets/js/lib/toastr/toastr.init.js"></script>--}}

    <script src="/admin-assets/js/custom.min.js"></script>

    <script src="/admin-assets/js/lib/datatables/datatables.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <script src="/admin-assets/js/lib/datatables/datatables-init.js"></script>

    <script>

        @if(Session::has('success'))
            toastr.success('{{ Session::get("success") }}',{
                "positionClass": "toast-top-full-width",
                timeOut: 5000,
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut",
                "tapToDismiss": false
            })
        @endif

        @if(Session::has('info'))
            toastr.info("{{ Session::get('info') }}",{
                "positionClass": "toast-top-full-width",
                timeOut: 5000,
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut",
                "tapToDismiss": false
            })
        @endif

        @if(Session::has('error'))
            toastr.error("{{ Session::get('error') }}",{
                "positionClass": "toast-top-full-width",
                timeOut: 5000,
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut",
                "tapToDismiss": false
            })
        @endif

    </script>

    </body>

</html>

resources/views/layouts/admin/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/admin-assets/images/favicon.png">
    <title>YouLog</title>

    <link href="/admin-assets/css/lib/toastr/toastr.min.css" rel="stylesheet">
    <!-- Bootstrap Core CSS -->
    <link href="/admin-assets/css/lib/bootstrap/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->

    <link href="/admin-assets/css/lib/calendar2/semantic.ui.min.css" rel="stylesheet">
    <link href="/admin-assets/css/lib/calendar2/pignose.calendar.min.css" rel="stylesheet">
    <link href="/admin-assets/css/lib/owl.carousel.min.css" rel="stylesheet" />
    <link href="/admin-assets/css/lib/owl.theme.default.min.css" rel="stylesheet" />
    <link href="/admin-assets/css/helper.css" rel="stylesheet">
    <link href="/admin-assets/css/style.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:** -->
    <!--[if lt IE 9]>
    <script src="https:**oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https:**oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="fix-header fix-sidebar">
<!-- Preloader - style you can find in spinners.css -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
</div>
<!-- Main wrapper  -->
<div id="main-wrapper">
    <!-- header header  -->
    <div class="header">
        <nav class="navbar top-navbar navbar-expand-md navbar-light">
            <!-- Logo -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url('admin/') }}">
                    <!-- Logo icon -->
                    <b><img src="/admin-assets/images/logo.png" alt="homepage" class="dark-logo" /></b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span><img src="/admin-assets/images/logo-text.png" alt="homepage" class="dark-logo" /></span>
                </a>
            </div>
            <!-- End Logo -->
            <div class="navbar-collapse">
                <!-- toggle and nav items -->
                <ul class="navbar-nav mr-auto mt-md-0">
                    <!-- This is  -->
                    <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                    <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                </ul>
                <!-- User profile and search -->
                <ul class="navbar-nav my-lg-0">
                    <!-- Profile -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="/{{Auth::user()->profile_picture}}" alt="profilepic" class="profile-pic" /></a>
                        <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                            <ul class="dropdown-user">
                                <li><a href="{{ url('/') }}">{{ __('content.visit_site_text') }}</a></li>
                                <li> <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                        {{ __('content.logout_text') }}
                                    </a>
                                </li>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- End header header -->

    @include('layouts.admin.left-sidebar')

    <!-- Page wrapper  -->
    <div class="page-wrapper">
        <!-- Container fluid  -->
        <div class="container-fluid">

            <button type="button" class="btn btn-success m-b-10 m-l-5" id="toastr-success-top-full-width" style="display:none;">Success</button>
            <button type="button" class="btn btn-info m-b-10 m-l-5" id="toastr-info-top-full-width" style="display:none;">Info</button>
            <button type="button" class="btn btn-warning m-b-10 m-l-5" id="toastr-warning-top-full-width" style="display:none;">Warning</button>
            <button type="button" class="btn btn-danger m-b-10 m-l-5" id="toastr-danger-top-full-width" style="display:none;">Error</button>

resources/views/layouts/admin/left-sidebar.blade.php
<!-- Left Sidebar  -->
<div class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-devider"></li>
                <li class="nav-label">Home</li>
                {{--<li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu">Dashboard <span class="label label-rouded label-primary pull-right">2</span></span></a>--}}
                    {{--<ul aria-expanded="false" class="collapse">--}}
                        {{--<li><a href="index.html">Ecommerce </a></li>--}}
                        {{--<li><a href="index1.html">Analytics </a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}
                <li> <a  href="{{url('admin/')}}" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu">Dashboard </span></a>

                <li class="nav-label">Members</li>
                <li> <a class="has-arrow" href="#" aria-expanded="false"><i class="fa fa-envelope"></i><span class="hide-menu">Users</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('users.create') }}">Create User</a></li>
                        <li><a href="{{ route('users.index') }}">Browse Users</a></li>
                    </ul>
                </li>
                <li> <a  href="{{ route('admins.index') }}" aria-expanded="false"><i class="fa fa-bar-chart"></i><span class="hide-menu">Admins</span></a></li>
                <li class="nav-label">Content</li>
                <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-suitcase"></i><span class="hide-menu">Categories </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('categories.create') }}">Add Category</a></li>
                        <li><a href="{{ route('categories.index') }}">Browse Categories</a></li>
                    </ul>
                </li>
                <li> <a href="{{ route('news.index') }}" aria-expanded="false"><i class="fa fa-suitcase"></i><span class="hide-menu">News</span></a>
                </li>

                <li class="nav-label">Payments</li>
                <li> <a  href="{{url('admin/distributefunds')}}" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu">Distribute Funds </span></a>
                </li>
                <li> <a  href="{{url('admin/payrequests')}}" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu">Payment Requests </span></a>
                </li>

                <li class="nav-label">Other</li>
                <li> <a href="{{ url('admin/ads') }}" aria-expanded="false"><i class="fa fa-book"></i><span class="hide-menu">Ads</span></a></li>
                <li> <a href="{{ url('admin/settings') }}" aria-expanded="false"><i class="fa fa-book"></i><span class="hide-menu">Settings</span></a></li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</div>
<!-- End Left Sidebar  -->

resources/views/layouts/admin/master.blade.php
@include('layouts.admin.header')


@yield('content')


@include('layouts.admin.footer')